-- Seed data from telnet.org/htm/places.htm
-- Fun & Utility Servers
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Time Server', 'india.colorado.edu', 13, 'telnet', 'Retrieve current time via telnet daytime protocol', 'network-tool', '["time","utility","daytime"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Vintage Mac GUI', 'vintagecomputing.com', 1984, 'telnet', 'GUI Mac demonstration with mouse support in the terminal', 'other', '["mac","vintage","gui","retro"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('NASA HORIZONS', 'horizons.jpl.nasa.gov', 6775, 'telnet', 'NASA JPL solar system ephemeris data and orbital mechanics', 'network-tool', '["nasa","space","science","jpl"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Doom Telnet', 'doom.w-graj.net', 666, 'telnet', 'Play Doom in your terminal over telnet', 'game', '["doom","fps","retro","game"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Free Internet Chess Server', 'freechess.org', 5000, 'telnet', 'Play chess online via telnet - one of the oldest internet chess servers', 'game', '["chess","multiplayer","classic"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Bitcoin Ticker', 'ticker.bitcointicker.co', 10080, 'telnet', 'Live Bitcoin price feed in your terminal', 'network-tool', '["bitcoin","crypto","ticker","finance"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('1984.ws', '1984.ws', 23, 'telnet', 'Edison Carter themed telnet server', 'other', '["retro","art","1984"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Telnet Wikipedia', 'telnet.wiki.gd', 23, 'telnet', 'Browse Wikipedia over telnet with AI assistant', 'network-tool', '["wikipedia","reference","ai"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('NyanCat Telnet', 'halite.md.vc', 23, 'telnet', 'NyanCat animation in your terminal', 'ascii-art', '["nyancat","animation","fun","meme"]', 'system', 'unknown');

-- BBS & Communities
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('ISCABBS', 'bbs.iscabbs.com', 23, 'telnet', 'Oldest continuously operating free online community', 'bbs', '["community","classic","historic"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Archaic Binary BBS', 'bbs.archaicbinary.net', 23, 'telnet', 'Classic BBS system', 'bbs', '["classic","retro"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Armageddon BBS', 'bbs.armageddonbbs.com', 23, 'telnet', 'Active BBS community', 'bbs', '["community"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Galacticomm BBS', 'gcomm.com', 23, 'telnet', 'BBS running on Galacticomm/MajorBBS platform', 'bbs', '["majorbbs","galacticomm"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('TextMMOde', 'TextMMOde.com', 23, 'telnet', 'Sands of Time and Deep Space text MMO', 'game', '["mmo","rpg","multiplayer"]', 'system', 'unknown');

-- MUDs & RPGs
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Ateraan', 'ateraan.com', 4002, 'telnet', 'New Worlds RPG - immersive text-based roleplaying', 'mud', '["rpg","roleplaying","fantasy"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Avalon RPG', 'avalon-rpg.com', 23, 'telnet', 'The Legend Lives - longrunning fantasy RPG', 'mud', '["rpg","fantasy","classic"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Cuban Bar', '52.88.68.92', 1234, 'telnet', 'Social MUD and talker', 'mud', '["social","talker","chat"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Legend of the Red Dragon', 'lord.stabs.org', 23, 'telnet', 'Classic BBS door game - slay the Red Dragon', 'game', '["lord","door-game","classic","rpg"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Hallowed Halls MUD', 'thehatshop.mudhosting.net', 3000, 'telnet', 'Fantasy MUD environment', 'mud', '["fantasy","multiplayer"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('New Moon MUD', 'eclipse.cs.pdx.edu', 7680, 'telnet', 'MUD hosted at Portland State University', 'mud', '["university","classic"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('BatMUD', 'batmud.bat.org', 23, 'telnet', 'One of the longest-running MUDs, Finnish-origin fantasy world', 'mud', '["fantasy","classic","finnish"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Forgotten Kingdoms', 'forgottenkingdoms.org', 4000, 'telnet', 'Forgotten Realms-based fantasy MUD', 'mud', '["fantasy","forgotten-realms","rpg"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Sheltering Sky MUSH', 'mush.shelteringcolorado.com', 2601, 'telnet', 'Colorado by Night - World of Darkness MUSH', 'mud', '["mush","world-of-darkness","roleplaying"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Igor MUD', 'igormud.org', 1701, 'telnet', 'Star Trek themed MUD', 'mud', '["star-trek","sci-fi"]', 'system', 'unknown');
INSERT OR IGNORE INTO entries (name, host, port, protocol, description, category, tags, submitted_by, status) VALUES ('Zombie MUD', 'zombiemud.org', 23, 'telnet', 'Horror-themed MUD with zombie survival', 'mud', '["horror","zombie","fantasy"]', 'system', 'unknown');
